# Generated by the sctx release workflow. Do not hand-edit.
class Sctx < Formula
  desc "Token-optimizing command wrapper for AI coding agents"
  homepage "https://synapctx.com/sctx/"
  # No explicit : Homebrew scans it from the archive URL, and
  #  reports a hardcoded one as redundant. Verified that the
  # scan yields the right value rather than assumed.
  license "MIT"

  on_macos do
    on_arm do
      url "https://github.com/synapctx/sctx/releases/download/v0.4.5/sctx_0.4.5_darwin_arm64.tar.gz"
      sha256 "27d50fd90368a2e09cce4ab7630f7575ba2f37e09a023cb879c3cc72b7f4480a"
    end
    on_intel do
      url "https://github.com/synapctx/sctx/releases/download/v0.4.5/sctx_0.4.5_darwin_amd64.tar.gz"
      sha256 "22b2696b2a77406e99446109cab16aaf5a4a65d5b6a8444b792a5173eacd991f"
    end
  end

  on_linux do
    on_arm do
      url "https://github.com/synapctx/sctx/releases/download/v0.4.5/sctx_0.4.5_linux_arm64.tar.gz"
      sha256 "324040534d8b67ae3836177f983425f443fcb7051b232b47a676a4bfa6de0608"
    end
    on_intel do
      url "https://github.com/synapctx/sctx/releases/download/v0.4.5/sctx_0.4.5_linux_amd64.tar.gz"
      sha256 "182b8fb8f5f3d60004b18e6201a52c2cb0f8e11a8d06fd819560c7b270efe46a"
    end
  end

  def install
    # Both binaries, into the same bin: `sctx watch` looks beside its own
    # executable first, so the helper it shipped with wins over any older
    # copy elsewhere on PATH.
    bin.install "sctx"
    bin.install "sctxd"
  end

  def caveats
    <<~EOS
      Tell the AI coding agents you use that sctx is available:
        sctx setup --install

      Everything works without an account. To connect one:
        sctx init
    EOS
  end

  test do
    assert_match "sctx", shell_output("#{bin}/sctx version")
    # sctxd is launched by `sctx watch` and reads its configuration on
    # stdin; given none it must refuse rather than wait for input.
    assert_match "sctxd", shell_output("#{bin}/sctxd </dev/null 2>&1", 2)
  end
end
