# Generated by the sctx release workflow. Do not hand-edit.
class Sctx < Formula
  desc "Token-optimizing command wrapper for AI coding agents"
  homepage "https://synapctx.com/sctx/"
  # No explicit : Homebrew scans it from the archive URL, and
  #  reports a hardcoded one as redundant. Verified that the
  # scan yields the right value rather than assumed.
  license "MIT"

  on_macos do
    on_arm do
      url "https://github.com/synapctx/sctx/releases/download/v0.3.0/sctx_0.3.0_darwin_arm64.tar.gz"
      sha256 "49cb61f0f96902f68c4dbb29d91ddcb9ab84d2cee8d4f30fedf123b780086451"
    end
    on_intel do
      url "https://github.com/synapctx/sctx/releases/download/v0.3.0/sctx_0.3.0_darwin_amd64.tar.gz"
      sha256 "19b11d36c8a8d30340bd4eecdfa365da06d432b64c19c75b3b6f41f50fe9aa73"
    end
  end

  on_linux do
    on_arm do
      url "https://github.com/synapctx/sctx/releases/download/v0.3.0/sctx_0.3.0_linux_arm64.tar.gz"
      sha256 "a9e42929a3452704ee73d1d1cf71fba4b769bbfe0c96576ee3197088bf5d732f"
    end
    on_intel do
      url "https://github.com/synapctx/sctx/releases/download/v0.3.0/sctx_0.3.0_linux_amd64.tar.gz"
      sha256 "18961768072eb123f99aa4b8f73c9016c6dcbacbcf99b311ee7113b662200da2"
    end
  end

  def install
    # Both binaries, into the same bin: `sctx watch` looks beside its own
    # executable first, so the helper it shipped with wins over any older
    # copy elsewhere on PATH.
    bin.install "sctx"
    bin.install "sctxd"
  end

  def caveats
    <<~EOS
      Tell the AI coding agents you use that sctx is available:
        sctx setup --install

      Everything works without an account. To connect one:
        sctx init
    EOS
  end

  test do
    assert_match "sctx", shell_output("#{bin}/sctx version")
    # sctxd is launched by `sctx watch` and reads its configuration on
    # stdin; given none it must refuse rather than wait for input.
    assert_match "sctxd", shell_output("#{bin}/sctxd </dev/null 2>&1", 2)
  end
end
