# Generated by the sctx release workflow. Do not hand-edit.
class Sctx < Formula
  desc "Token-optimizing command wrapper for AI coding agents"
  homepage "https://synapctx.com/sctx/"
  # No explicit : Homebrew scans it from the archive URL, and
  #  reports a hardcoded one as redundant. Verified that the
  # scan yields the right value rather than assumed.
  license "MIT"

  on_macos do
    on_arm do
      url "https://github.com/synapctx/sctx/releases/download/v0.7.3/sctx_0.7.3_darwin_arm64.tar.gz"
      sha256 "2e112b3e055d3e2d33763011c9d2454b8e033795872909e235136981995d95ed"
    end
    on_intel do
      url "https://github.com/synapctx/sctx/releases/download/v0.7.3/sctx_0.7.3_darwin_amd64.tar.gz"
      sha256 "ed7c1acaabb42f0f12a17027808ed0a7c3cd9df846111b90d91a4ecbde87ac95"
    end
  end

  on_linux do
    on_arm do
      url "https://github.com/synapctx/sctx/releases/download/v0.7.3/sctx_0.7.3_linux_arm64.tar.gz"
      sha256 "4a3def248a442726a3f9da8df1b0b241807b55acdc2f415799992eb3364035e4"
    end
    on_intel do
      url "https://github.com/synapctx/sctx/releases/download/v0.7.3/sctx_0.7.3_linux_amd64.tar.gz"
      sha256 "9f7aad580ad1e6f70959777a1db2e9686a03b89e2c87c6a7b3ce0eb15e1778ab"
    end
  end

  def install
    # Both binaries, into the same bin: `sctx watch` looks beside its own
    # executable first, so the helper it shipped with wins over any older
    # copy elsewhere on PATH.
    bin.install "sctx"
    bin.install "sctxd"
  end

  def caveats
    <<~EOS
      Tell the AI coding agents you use that sctx is available:
        sctx setup --install

      Everything works without an account. To connect one:
        sctx init
    EOS
  end

  test do
    assert_match "sctx", shell_output("#{bin}/sctx version")
    # sctxd is launched by `sctx watch` and reads its configuration on
    # stdin; given none it must refuse rather than wait for input.
    assert_match "sctxd", shell_output("#{bin}/sctxd </dev/null 2>&1", 2)
  end
end
